development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mastery_dev
  pool: 5
  username: mastery
  password: '123456'
  port: 54321

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mastery_test
  pool: 5
  username: mastery
  password: '123456'
  port: 54321
